### ISSUE TITLE
Document endpoints and return objects

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-middleware#10] opened 2019-01-23 10:11 UTC
Could you guys add what is the expected result for each endpoint?

In such a way we can develop our own compatible middleware. 👍

**Comment by jsnewby** [comment] 2019-01-28 15:18
Duplicate of 12

This will be addressed by updating swagger

**Comment by shekhar-shubhendu** [comment] 2019-07-17 11:44
added swagger file which will be updated whenever new endpoint is added or updated

**Closed by shekhar-shubhendu** 2019-07-17 11:44 UTC
